### PR TITLE
Replace capital letters in logs

### PR DESCRIPTION
**Pull request by UsamaAmjad**

### CODE REVIEW

**Comment by noseglid** [comment]
I can see what you're doing, but why? :)

**Comment by UsamaAmjad** [comment]
> I can see what you're doing, but why? :)

I was getting linting suggestions to use small letters so I thought to update them. Thought its convention?

**Comment by noseglid** [comment]
For errors absolutely. Because errors often printed at the top with colons, so you do
```
logrus.Errorf("Something went wrong: %v", err)
```

and then errors have lower case letter.

Log printouts should still be capital letters though, as they initialize the sentance.

**Comment by UsamaAmjad** [comment]
> For errors absolutely. Because errors often printed at the top with colons, so you do
> 
> ```
> logrus.Errorf("Something went wrong: %v", err)
> ```
> 
> and then errors have lower case letter.
> 
> Log printouts should still be capital letters though, as they initialize the sentance.

Aha thanks! I misunderstood it and open another PR 😄

**Comment by noseglid** [comment]
I think this one
```
return errors.New("invalid status: " + result.Status)
```
is good though! That should be lower case!

**Comment by johan-lejdung** [comment]
Another way of logging errors with logrus in a structured way is 👌

```
logrus.WithError(err).Error("Something went wrong")
```

Then the error shows up as a structured field in the output instead of being part of the message

**Pull request closed without merging**
